import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
// import HeaderComp from "../components/headerComponent"
var text = "LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. PRAESENT NON RISUS AC LECTUS MALESUADA SODALES. SED ACCUMSAN, JUSTO A ULLAMCORPER FINIBUS, DUI LECTUS CONSEQUAT URNA, VESTIBULUM TEMPUS SEM LECTUS IN EST. QUISQUE TINCIDUNT FELIS A TEMPUS MOLESTIE. NAM LAOREET AT URNA NEC SAGITTIS. NUNC BIBENDUM TINCIDUNT DAPIBUS. MORBI VOLUTPAT RUTRUM FELIS, NON CONGUE LOREM PLACERAT AT. UT JUSTO TURPIS, SEMPER A PORTTITOR A, PHARETRA NON LOREM. DONEC SCELERISQUE EROS SIT AMET ODIO CONDIMENTUM ORNARE. SED QUIS TURPIS ORCI. PROIN QUIS LACINIA ELIT. NULLA EU TELLUS VITAE LIGULA DICTUM PRETIUM. PHASELLUS TRISTIQUE PORTA DIGNISSIM. NAM IACULIS NIBH AT NISL VESTIBULUM, QUIS MATTIS SEM CONVALLIS. LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. NAM SED TEMPUS JUSTO, IN FACILISIS DUI. VESTIBULUM PULVINAR FACILISIS EFFICITUR. AENEAN RUTRUM, ODIO SIT AMET IACULIS FEUGIAT, LECTUS NUNC TINCIDUNT IPSUM, NON DIGNISSIM AUGUE NIBH ET LIBERO. PELLENTESQUE ORCI LEO, VEHICULA UT TEMPOR VITAE, ELEMENTUM ID TURPIS. SED CONGUE QUAM EGET DOLOR CONVALLIS, EGET ULTRICES LIGULA LACINIA. ETIAM A COMMODO ORCI. PRAESENT SODALES AT IPSUM VITAE PLACERAT. NULLA FACILISI. CURABITUR NON MAGNA LIBERO. NAM VESTIBULUM URNA MI, VEL FRINGILLA EX PORTTITOR VITAE. LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. DUIS PHARETRA NON ERAT QUIS SODALES. SED TINCIDUNT VEHICULA ALIQUAM. SED FEUGIAT EU LIGULA AC CURSUS. FUSCE ORNARE EROS EST, EU FEUGIAT LIGULA IMPERDIET SED. NAM NISI DUI, ULTRICIES A AUGUE SIT AMET, ALIQUAM GRAVIDA SAPIEN. FUSCE ERAT ARCU, CONVALLIS UT SEM ID, PELLENTESQUE TINCIDUNT SAPIEN. CLASS APTENT TACITI SOCIOSQU AD LITORA TORQUENT PER CONUBIA NOSTRA, PER INCEPTOS HIMENAEOS. DONEC VITAE MI IN MI BIBENDUM VESTIBULUM EGET IN NEQUE. CRAS CURSUS MASSA SIT AMET FELIS FEUGIAT, ET VESTIBULUM METUS EUISMOD. PROIN EU NULLA COMMODO NUNC DAPIBUS MOLESTIE. AENEAN TEMPOR MAXIMUS MAURIS, A DICTUM DIAM EUISMOD UT. ETIAM LUCTUS MI IN EX FERMENTUM FERMENTUM. SED SAPIEN NUNC, SUSCIPIT AC TURPIS ID, POSUERE BIBENDUM ODIO. NULLAM CONSEQUAT LIBERO A ELIT ELEIFEND CONDIMENTUM. UT MALESUADA EFFICITUR VELIT, AC ALIQUAM AUGUE FEUGIAT ET. INTEGER NON DIGNISSIM TURPIS, VEL EUISMOD NULLA. NUNC EU NISL BIBENDUM, TEMPOR EST VITAE, PORTA NISI. PELLENTESQUE UT LIGULA DIGNISSIM, CONSEQUAT ORCI QUIS, GRAVIDA ANTE. ALIQUAM AUCTOR EROS NEC ARCU VENENATIS GRAVIDA. PROIN TINCIDUNT RUTRUM EROS. UT QUIS SAPIEN TEMPUS, FERMENTUM NULLA SIT AMET, RUTRUM DOLOR. ETIAM CONDIMENTUM A LECTUS SIT AMET DAPIBUS. VESTIBULUM SED ARCU ORCI. NAM ELEMENTUM ERAT NEC NUNC LACINIA, VITAE AUCTOR NIBH LACINIA. NUNC VEL PURUS QUIS NISI TEMPOR CONGUE. PROIN FRINGILLA VESTIBULUM MOLESTIE. NUNC AC LOREM SIT AMET EROS GRAVIDA PORTTITOR. FUSCE RUTRUM PURUS TRISTIQUE LECTUS CONGUE VENENATIS. PRAESENT NEC VELIT SAPIEN. DONEC COMMODO DIAM NON NUNC FERMENTUM, VEL ULTRICES IPSUM SAGITTIS. NUNC TINCIDUNT MOLESTIE SEM, A POSUERE SEM ULTRICES VEL. MAURIS SEMPER EFFICITUR ERAT. VESTIBULUM VOLUTPAT AUCTOR LACUS, IN SEMPER LACUS CURSUS UT. INTEGER POSUERE EU DUI A PELLENTESQUE. DUIS LOREM LIGULA, ELEMENTUM ET QUAM AT, LAOREET VULPUTATE NISI. NUNC EGET EUISMOD LECTUS, ET FEUGIAT IPSUM. PELLENTESQUE PHARETRA JUSTO AT IPSUM COMMODO, VITAE VIVERRA NEQUE EGESTAS. NULLA AC EX EGET TORTOR MOLLIS CONGUE ID UT RISUS. NUNC RUTRUM IN LIGULA VITAE BLANDIT. ALIQUAM UT AUGUE TELLUS. IN NISL RISUS, TINCIDUNT AC TORTOR ID, LOBORTIS DICTUM NEQUE. LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. VIVAMUS A ORNARE EROS, AC RUTRUM ARCU. IN CONSEQUAT PORTA NISL, NON FRINGILLA DUI FINIBUS AT. DONEC A SCELERISQUE JUSTO, ET ALIQUET JUSTO. IN ELEMENTUM FELIS VEL AUGUE SEMPER, GRAVIDA LAOREET METUS TEMPOR. QUISQUE DIGNISSIM METUS ID EUISMOD ELEIFEND. NULLAM SED TURPIS PORTA, ALIQUET LACUS NEC, PLACERAT AUGUE. VIVAMUS UT DAPIBUS EROS. ALIQUAM QUIS PLACERAT NULLA. SED SOLLICITUDIN ELIT MI, EU HENDRERIT NIBH ULTRICES VEL. ALIQUAM SEMPER EFFICITUR CONGUE. FUSCE CONGUE MAGNA ID CURSUS ACCUMSAN. NULLAM VITAE VENENATIS NIBH, ET MOLLIS EST. FUSCE ULLAMCORPER EX A EX FAUCIBUS MATTIS. DONEC NEC TEMPOR SEM. DONEC SODALES ANTE NUNC, QUIS EGESTAS DIAM FEUGIAT NEC. MAECENAS SED PURUS LOREM. NULLAM TRISTIQUE TEMPOR FERMENTUM. NUNC UT MAURIS AC IPSUM SOLLICITUDIN TINCIDUNT. NUNC ULTRICIES DIAM SED PURUS LUCTUS FEUGIAT ET SIT AMET SEM. ETIAM FINIBUS RUTRUM ALIQUET. QUISQUE CONVALLIS, LACUS SED MOLESTIE VENENATIS, NISI MASSA SAGITTIS NISI, AT TINCIDUNT SAPIEN SAPIEN AC EX. MORBI COMMODO VEHICULA VEHICULA. NAM SOLLICITUDIN ERAT NON NISI DAPIBUS CONVALLIS. CRAS DAPIBUS BIBENDUM TORTOR, SIT AMET CONDIMENTUM AUGUE LAOREET ET. SED ALIQUAM ARCU VEL AUGUE PELLENTESQUE EFFICITUR. IN CONSECTETUR ACCUMSAN ODIO EU FRINGILLA. MAECENAS PRETIUM DUI AT NISL IMPERDIET, ID FAUCIBUS NISL RHONCUS. NUNC DICTUM NIBH EU NISI COMMODO, AT FEUGIAT MASSA ELEMENTUM. INTEGER ET LOREM DAPIBUS, RUTRUM NUNC QUIS, MAXIMUS LACUS. NULLA FACILISIS NEQUE AT CONSECTETUR VARIUS. ALIQUAM AUCTOR, SEM VITAE DIGNISSIM ELEIFEND, SEM VELIT ELEMENTUM DUI, AT SUSCIPIT LOREM ORCI NEC EX. DONEC NON HENDRERIT EST. SUSPENDISSE RHONCUS JUSTO IN NIBH SODALES, VEHICULA LUCTUS LOREM AUCTOR. MAECENAS INTERDUM URNA UT VOLUTPAT DAPIBUS. PROIN UT IACULIS ERAT, ET PLACERAT LACUS. DONEC UT LOREM CURSUS, VIVERRA ODIO VITAE, MOLESTIE NISI. ORCI VARIUS NATOQUE PENATIBUS ET MAGNIS DIS PARTURIENT MONTES, NASCETUR RIDICULUS MUS. NULLAM PELLENTESQUE PURUS VOLUTPAT FELIS PHARETRA CONSEQUAT. NULLAM CONDIMENTUM NEC EROS NEC BIBENDUM. NAM ET ORNARE TELLUS, VEL ELEIFEND LEO. SUSPENDISSE TINCIDUNT LEO LACUS, TEMPOR FAUCIBUS METUS INTERDUM QUIS. AENEAN NEQUE MASSA, CONSEQUAT UT TURPIS PRETIUM, IACULIS GRAVIDA AUGUE. DUIS SCELERISQUE VENENATIS DIAM, NON CONVALLIS URNA. ALIQUAM LACINIA IN DOLOR NEC ACCUMSAN. SED FACILISIS TINCIDUNT MOLLIS. VESTIBULUM SIT AMET FACILISIS SEM, ID PORTTITOR SAPIEN. PROIN NEC QUAM URNA. NUNC MATTIS RISUS AT VELIT ACCUMSAN LACINIA. IN MOLESTIE TINCIDUNT LEO IN SCELERISQUE. VESTIBULUM GRAVIDA LIBERO PURUS, EU VEHICULA NUNC DICTUM UT. INTERDUM ET MALESUADA FAMES AC ANTE IPSUM PRIMIS IN FAUCIBUS. NUNC SED SAGITTIS MASSA. IN LUCTUS IMPERDIET EST, VEL SAGITTIS DIAM FEUGIAT NEC. VIVAMUS NISI NIBH, VIVERRA EGET TURPIS AC, ULLAMCORPER MATTIS DUI. NAM FERMENTUM TORTOR LACINIA LIBERO PELLENTESQUE ALIQUAM. ALIQUAM SED PULVINAR MI. ALIQUAM CONSEQUAT ID ENIM CONVALLIS TEMPUS. SUSPENDISSE LUCTUS RUTRUM ORCI NEC SOLLICITUDIN. INTEGER QUIS URNA SODALES QUAM ORNARE RUTRUM. UT JUSTO MI, TINCIDUNT ID ULLAMCORPER AT, FERMENTUM AT LOREM. INTEGER EUISMOD ANTE ET DUI ULLAMCORPER IMPERDIET. CURABITUR ANTE URNA, ALIQUET AC SAPIEN VITAE, VENENATIS ACCUMSAN NEQUE. DONEC ELIT EX, SAGITTIS AT RISUS A, LACINIA PULVINAR NUNC. PRAESENT MAURIS TORTOR, LACINIA VEL TORTOR SED, FERMENTUM TEMPOR EST. ETIAM NEC HENDRERIT METUS. CRAS POSUERE EUISMOD TORTOR, VEL SEMPER TELLUS VESTIBULUM AC. CURABITUR SIT AMET ORNARE EX. MAECENAS IMPERDIET VITAE ODIO ET DIGNISSIM. DUIS FRINGILLA ALIQUET CONSEQUAT. CURABITUR DIGNISSIM NEQUE UT MATTIS ELEIFEND. PHASELLUS PORTTITOR SUSCIPIT CONSEQUAT. MAECENAS MAGNA ERAT, TINCIDUNT EU RISUS MAXIMUS, EUISMOD PRETIUM DUI. VIVAMUS ODIO LIGULA, DIGNISSIM AC JUSTO VITAE, BIBENDUM VIVERRA ERAT. VIVAMUS POSUERE, MASSA LACINIA TEMPOR VULPUTATE, ERAT NEQUE EFFICITUR URNA, NON LACINIA RISUS ANTE NON NISL. MORBI SAGITTIS TELLUS AT ORCI CONSEQUAT, VULPUTATE POSUERE LOREM LOBORTIS. FUSCE NEC DOLOR NON MASSA VOLUTPAT VENENATIS. SED EGET LECTUS VARIUS, RHONCUS MI AT, FACILISIS PURUS. NUNC VEL LACINIA LOREM. INTERDUM ET MALESUADA FAMES AC ANTE IPSUM PRIMIS IN FAUCIBUS. DONEC ACCUMSAN ELEMENTUM ARCU VITAE TRISTIQUE. ALIQUAM SEM MAGNA, SUSCIPIT ET LOBORTIS AC, CONGUE EGET TORTOR. PHASELLUS CURSUS TEMPOR QUAM EU VENENATIS. MAECENAS EX URNA, BIBENDUM UT DIGNISSIM AC, FACILISIS SIT AMET ODIO. INTEGER SEMPER TELLUS NEC ENIM EGESTAS PORTA. INTEGER ULTRICES COMMODO NISI VENENATIS RUTRUM. MAURIS ELEIFEND LECTUS EST, VITAE PORTTITOR URNA CONVALLIS EGET. IN SAGITTIS ORCI VEL SAPIEN CONSECTETUR VOLUTPAT. VESTIBULUM MAGNA NISI, VIVERRA VITAE SEM AC, POSUERE VOLUTPAT NULLA. NULLA ENIM NEQUE, VOLUTPAT ET VELIT VEL, ELEIFEND ACCUMSAN QUAM. IN UT FACILISIS LACUS. SED SED ODIO ARCU. PELLENTESQUE VESTIBULUM ULTRICES PURUS SED SEMPER. PROIN URNA DUI, PHARETRA AC FAUCIBUS ET, SAGITTIS"

const About = () => (
    <div>
        <Head>
            <title>Mustafa Berat ARU - Kişisel Web Sitesi</title>
            <link rel="icon" href="/m.png" href="/#" />
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
                integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"></link>
        </Head>

        <header className="header">
            <div className="container">
                <a className="header-logo" href="http://mustafaberat.now.sh/">
                    <img src="/m.png" alt="MLOGO"></img>
                </a>
                <div className="header-buttons">
                    <Link href="http://mustafaberat.now.sh/">
                        <a className="header-button-aboutMe header-button">Home Page</a>
                    </Link>
                </div>
            </div>
        </header>

        <section className="section">
            <div className="container">
                <h1 className="name-surname">About Me</h1>
                <p className="my-title">{text}</p>
                <article className="social-media-links about-social-media-area">
                    <Link href="https://www.instagram.com/mustafaberatt/">
                        <a className="social-media-instagram social-media-common" target="blank">
                            <i className="fab fa-instagram"></i>
                        </a></Link>
                    <Link href="https://github.com/mustafaberat/">
                        <a className="social-media-github social-media-common" target="blank">
                            <i className="fab fa-github-alt"></i>
                        </a></Link>
                    <Link href="https://www.facebook.com/mustafaberatt">
                        <a className="social-media-facebook social-media-common" target="blank">
                            <i className="fab fa-facebook-f"></i>
                        </a></Link>
                    <Link href="https://codepen.io/mustafaberatt">
                        <a className="social-media-codepen social-media-common" target="blank">
                            <i className="fab fa-codepen"></i>
                        </a></Link>
                    <Link href="https://www.linkedin.com/in/mustafaberatt/">
                        <a className="social-media-linkedin social-media-common" target="blank">
                            <i className="fab fa-linkedin-in"></i>
                        </a></Link>
                </article>
            </div>
        </section>
    </div>
)
export default About
